### PR TITLE
Update Rocket dependency to version 0.2.0

### PR DESCRIPTION
**Pull request by Ferdi265**
I'm trying to use this library with Rocket, so I updated the dependency to version 0.2.0.

### CODE REVIEW

**Comment by lfairy** [comment]
Thanks, didn't realize Rocket 0.2 was released already.

Is there a way to declare support for both versions 0.1 and 0.2 simultaneously? That should ease the transition path for those still on Rocket 0.1.

**Comment by TheNeikos** [comment]
I think `<=1.2` should work, per http://doc.crates.io/specifying-dependencies.html

**Comment by lfairy** [comment]
I'd prefer `>= 0.1.2, < 0.3` instead since that keeps the lower bound

**Comment by Ferdi265** [comment]
Changed to lfairy's suggestion.

**Comment by lfairy** [comment]
Looks good, thanks!

**Comment by lfairy** [comment]
Released as [0.16.1](https://crates.io/crates/maud/0.16.1).

**Comment by Ferdi265** [comment]
Thanks, I'll start using this then 👍

**Pull request merged**
